# Configuración del Motor de Bonita BPM
bonita.url=http://localhost:8082/bonita
bonita.username=install
bonita.password=install

# Configuración por defecto de procesos en Bonita Studio
bonita.process.version=1.0.0
bonita.process.consultar=ConsultarSaldo
bonita.process.retirar=Retirar
bonita.process.depositar=Depositar
bonita.process.transferir=Transferir
